//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterPolEntities : DbContext
    {
        public MasterPolEntities()
            : base("name=MasterPolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Материал> Материал { get; set; }
        public virtual DbSet<Партнер> Партнер { get; set; }
        public virtual DbSet<ПродуктыПартнера> ПродуктыПартнера { get; set; }
        public virtual DbSet<Продукция> Продукция { get; set; }
        public virtual DbSet<ТипМатериала> ТипМатериала { get; set; }
        public virtual DbSet<ТипПартнера> ТипПартнера { get; set; }
        public virtual DbSet<ТипПродукции> ТипПродукции { get; set; }
    }
}
