//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Партнер
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Партнер()
        {
            this.ПродуктыПартнера = new HashSet<ПродуктыПартнера>();
        }
    
        public int КодПартнера { get; set; }
        public string НаименованиеПартнера { get; set; }
        public string Директор { get; set; }
        public string Почта { get; set; }
        public string Телефон { get; set; }
        public string ЮрАдрес { get; set; }
        public Nullable<double> ИНН { get; set; }
        public Nullable<double> Рейтинг { get; set; }
        public int ТипПартнера { get; set; }
    
        public virtual ТипПартнера ТипПартнера1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродуктыПартнера> ПродуктыПартнера { get; set; }
    }
}
