//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.ПродуктыПартнера = new HashSet<ПродуктыПартнера>();
        }
    
        public int КодПродукции { get; set; }
        public string НаименованиеПродукции { get; set; }
        public Nullable<int> Артикул { get; set; }
        public Nullable<double> МинСтоимостьДляПартнера { get; set; }
        public Nullable<int> ТипПродукции { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродуктыПартнера> ПродуктыПартнера { get; set; }
        public virtual ТипПродукции ТипПродукции1 { get; set; }
    }
}
