//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПродуктыПартнера
    {
        public int КодПродуктаПартнера { get; set; }
        public Nullable<int> Продукция { get; set; }
        public Nullable<int> НаименованиеПартнера { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Партнер Партнер { get; set; }
        public virtual Продукция Продукция1 { get; set; }
    }
}
